services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yoPrintApp
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - QUEUE_CONNECTION=redis
    entrypoint: [ "sh", "/var/www/entrypoint.sh" ]
    command: php artisan serve --host=0.0.0.0 --port=8000

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - 6379:6379

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    command: php artisan queue:work
    depends_on:
      - redis
  horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    command: php artisan horizon
    depends_on:
      - redis
